### ISSUE TITLE
network - declare devbox as external

### ISSUE THREAD

**Issue by mborne** [mborne/docker-devbox#17]
This will warning on `docker compose down` :

```yaml
networks:
  default:
    name: devbox
    external: true
```

See [docs.docker.com - Use a pre-existing network](https://docs.docker.com/compose/networking/#use-a-pre-existing-network)
