### ISSUE TITLE
traefik - remove traefik.http.routers.{NAME}.tls=true in docker-compose.yml files

### ISSUE THREAD

**Issue by mborne** [mborne/docker-devbox#20]
* It enables tls on "web" and "websecure".
* It can be configured globally : 

```toml
[entryPoints]
  [entryPoints.web]
    address = ":80"
  # redirect http to https
  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http]
    tls = true
```
