### ISSUE TITLE
Kyverno - experiment some configs to ensure that kube-system is ignored...

### ISSUE THREAD

**Issue by mborne** [mborne/docker-devbox#58]
```smarty
admissionController:
  replicas: 3
  metricsService:
    create: true
    annotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"
backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2
# config:
#   webhooks:
#     # Exclude namespaces
#     - namespaceSelector:
#         matchExpressions:
#         - key: kubernetes.io/metadata.name
#           operator: NotIn
#           values:
#             - kube-system
#             - kube-public
#             - kube-node-lease
```

**Comment by mborne** [comment]
Context : https://help.ovhcloud.com/csm/fr-public-cloud-kubernetes-install-kyverno?id=kb_article_view&sysparm_article=KB0055165#policy-2-create-a-configmap-in-all-namespaces-excepted-kube-system-kube-public-and-kyverno

**Comment by mborne** [comment]
## Test 2

```
admissionController:
  replicas: 3
  metricsService:
    create: true
    annotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"

backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2

config:
  webhooks:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
```

```bash
kubectl get validatingwebhookconfigurations kyverno-resource-validating-webhook-cfg -o jsonpath='{ .webhooks[].namespaceSelector }' | jq
```

```json
{
  "matchExpressions": [
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kube-system",
        "kube-public",
        "kube-node-lease"
      ]
    },
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kyverno"
      ]
    }
  ]
}
```

**Comment by mborne** [comment]
## Test 3

> current config 

```yaml
admissionController:
  replicas: 3
  metricsService:
    create: true
    annotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"

backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2
```

```bash
kubectl get validatingwebhookconfigurations kyverno-resource-validating-webhook-cfg -o jsonpath='{ .webhooks[].namespaceSelector }' | jq
```

```json
{
  "matchExpressions": [
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kube-system"
      ]
    },
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kyverno"
      ]
    }
  ]
}
```

=> **kube-system ignored by default**

**Comment by mborne** [comment]
# Overview

```bash
for i in $(kubectl get validatingwebhookconfigurations -o name);
do
  echo "# $i" ;
  kubectl get $i -o jsonpath='{ .webhooks[].namespaceSelector }' | jq ;
done
```

```
# validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook
{
  "matchExpressions": [
    {
      "key": "cert-manager.io/disable-validation",
      "operator": "NotIn",
      "values": [
        "true"
      ]
    },
    {
      "key": "name",
      "operator": "NotIn",
      "values": [
        "cert-manager"
      ]
    }
  ]
}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-cleanup-validating-webhook-cfg
{}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-exception-validating-webhook-cfg
{}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-global-context-validating-webhook-cfg
{}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-policy-validating-webhook-cfg
{}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-resource-validating-webhook-cfg
{
  "matchExpressions": [
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kube-system",
        "kube-public",
        "kube-node-lease"
      ]
    },
    {
      "key": "kubernetes.io/metadata.name",
      "operator": "NotIn",
      "values": [
        "kyverno"
      ]
    }
  ]
}
# validatingwebhookconfiguration.admissionregistration.k8s.io/kyverno-ttl-validating-webhook-cfg
{}
```

**=> only used by kyverno-resource-validating-webhook-cfg**

**Comment by mborne** [comment]
No problem with `validationFailureAction: Audit`

```yaml
podSecurityStandard: restricted
validationFailureAction: Audit
```

No problem when disabling rules for namespaces ...

```yaml
validationFailureAction: Enforce
validationFailureActionOverrides:
  all:
    - action: audit
      namespaces:
        - loki
        - fluent
        - traefik
        - nginx-system
```
